In [7]:
import numpy as np
import random as rand

a = np.array([1,2,3,4,5])
print(a)

a[3]


[1 2 3 4 5]


4

In [11]:
rand = np.random.RandomState(52) #keeps a generated random number same for all the random samples 22 is a assigned state
x = rand.randint(100, size=10) #max value will be 100 for each element and size: number of elements are generated
print(x)

[28 11 13 23 86 28 32 69 11 91]


In [10]:
rand = np.random.RandomState(22)
x = rand.randint(10, size=10)
print(x)

[5 4 0 4 6 6 4 8 4 2]


In [13]:
#1D array

print([x[3],x[4],x[5]]) # direct method

ind = [3,4,5] #list of idex array
x[ind] #accessing the inxed array and the list elements

[23, 86, 28]


array([23, 86, 28])

In [14]:
#2D array
ind = np.array([[3,7],
                [4,5]])
print(ind)
print(x[ind])

[[3 7]
 [4 5]]
[[23 69]
 [86 28]]


In [18]:
ind = np.array([[3,7,9],
                [4,5,1],
                ])
print("Index matrix: \n",ind)
print("Accessed elements from the random list through indexed matrix:\n ",x[ind])

Index matrix: 
 [[3 7 9]
 [4 5 1]]
Accessed elements from the random list through indexed matrix:
  [[23 69 91]
 [86 28 11]]


In [25]:
x2 = np.array([(1,2,3),(11,22,33)])

print("defined array:\n ",x2)
print("Dimention of the array is",x2.ndim,"D")
print("Each item contains", x2.itemsize,"bytes")
print("array size is",x2.shape)
print("Each item is of the type is", x2.dtype)

defined array:
  [[ 1  2  3]
 [11 22 33]]
Dimention of the array is 2 D
Each item contains 4 bytes
array size is (2, 3)
Each item is of the type is int32


In [26]:
print(np.add.reduce(x2)) #column sum
print(sum(x2)) #column sum
print(np.sum(x2)) #sum of all the elements

[12 24 36]
[12 24 36]
72


In [30]:
#reshape
a = np.array([[1,2],[3,4],[5,6]])
print("original array:\n",a)
ar1 = a.reshape(2,3)
ar2 = a.reshape(6,1)
ar3 = a.reshape(1,6)
print("reshaped array: \n",ar1,
      "\n6x1: \n",ar2,
      "\n1x6: \n",ar3)

original array:
 [[1 2]
 [3 4]
 [5 6]]
reshaped array: 
 [[1 2 3]
 [4 5 6]] 
6x1: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 
1x6: 
 [[1 2 3 4 5 6]]


In [5]:
import numpy as np
a = np.arange(12)
print(a)

#putting elements in 2D
a = np.arange(12).reshape((3,4))
print(a)

# combined indexing
print("\naccessing the elements \n",a[1,[2,0,1]])

#accessing a row

print("\naccessing the row  \n",a[1,[0,1,2,3]])

#bottom square access
print("\n bottomsquare elements access\n",(a[2:4,1:3]))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

accessing the elements 
 [6 4 5]

accessing the row  
 [4 5 6 7]

 bottomsquare elements access
 [[ 9 10]]


In [59]:
#aggregations-computation on array

print("array:\n",a)
print("The max element of matrix:",a.max())
print("the minimum the the matrix:",a.min())
print("the sum of all matrix elements:",a.sum())
print("max val of a column:" , a.max(axis=0))
print("min of row:", a.min(axis=1))
print("sum of row:",a.sum(axis=1))
print("sum of column: ",a.sum(axis=0))
print("sqrt of all elements: \n", np.sqrt(a))
print("std deviation of array elements: \n",np.std(a))
print("average of the vals: ",np.average(a))

array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The max element of matrix: 11
the minimum the the matrix: 0
the sum of all matrix elements: 66
max val of a column: [ 8  9 10 11]
min of row: [0 4 8]
sum of row: [ 6 22 38]
sum of column:  [12 15 18 21]
sqrt of all elements: 
 [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
std deviation of array elements: 
 3.452052529534663
average of the vals:  5.5


In [61]:
#arithematic operation on arrays:

c = np.array([[1,2,30],[10,15,4]])
print("array1 = \n",c)
b = np.array([[1,2,30],[10,15,4]])
print("array2 = \n",b)

print('sum of both arrays\n',c+b)
print('differsnce of arrays\n', c-b)
print('multiplication of arrays\n', c*b)
print('division of arrays\n',c/b)
print('scalar mu:\n ' , c*3)

array1 = 
 [[ 1  2 30]
 [10 15  4]]
array2 = 
 [[ 1  2 30]
 [10 15  4]]
sum of both arrays
 [[ 2  4 60]
 [20 30  8]]
differsnce of arrays
 [[0 0 0]
 [0 0 0]]
multiplication of arrays
 [[  1   4 900]
 [100 225  16]]
division of arrays
 [[1. 1. 1.]
 [1. 1. 1.]]
scalar mu:
  [[ 3  6 90]
 [30 45 12]]


In [66]:
#array concatenation
print("array b\n{} \n array c\n{}".format(b,c))
print("\nVertical cocatenation:\n", np.vstack((b,c)))
print("\nHorizontal concatenation\n",np.hstack((b,c))) # 

array b
[[ 1  2 30]
 [10 15  4]] 
 arrayc
[[ 1  2 30]
 [10 15  4]]

Vertical cocatenation:
 [[ 1  2 30]
 [10 15  4]
 [ 1  2 30]
 [10 15  4]]

Horizontal concatenation
 [[ 1  2 30  1  2 30]
 [10 15  4 10 15  4]]


In [1]:
# 30-08-2023

In [9]:
import numpy as np
a = np.arange(9)
print(a)

#putting elements in 2D
a = np.arange(9).reshape((3,3))
print(a)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
# slicing of matrix

# top right square
print(a[:2,1:])
print(a[0:2,1:3])

# bottom row 
print(a[-1,:])


[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[6 7 8]


In [22]:
#Booolean Indexing

names = np.array(['bob','joe','will','bob'])
print(names)



#putting elements in 2D
a = np.arange(12).reshape((4,3))
print(a)


print(names == "bob")
a[names == 'bob']

logic1 = (names == 'bob') | (names == 'joe')
print('logic 1: ', logic1)
print(a[logic1])

['bob' 'joe' 'will' 'bob']
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ True False False  True]
logic 1:  [ True  True False  True]
[[ 0  1  2]
 [ 3  4  5]
 [ 9 10 11]]


In [46]:
#Fancy indexing
# it allows us to index an array using another array, a list or a sequence  

In [47]:
a = np.arange(36).reshape((6,6))
print(a)

print('\nfirst array: ',a[(0,1,2,3,4),(1,2,3,4,5)])

print('\nsecond array:\n',a[3:,[0,2,5]])

bool1 = np.array([1,0,1,0,0,1],dtype=bool)
print('\nthird array:',a[bool1,2])
print('--------------------------------')
arr = []
for i in range(0,5):
    element = a[i,(i+1)]
    arr.append(element)
np.array(arr)
print(arr)
type(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

first array:  [ 1  8 15 22 29]

second array:
 [[18 20 23]
 [24 26 29]
 [30 32 35]]

third array: [ 2 14 32]
--------------------------------
[1, 8, 15, 22, 29]


list

In [62]:
#sorting arrays
#quick sort

x = np.array([10,7,1,8,9,6,4,3,2])
print('array: ', x)

print(np.sort(x))
print(np.argsort(x))
print('-------------------------------------')
print(x[np.argsort(-x)]) #ascending order or np.sort(x)[::-1]
print(np.argsort(-x))

array:  [10  7  1  8  9  6  4  3  2]
[ 1  2  3  4  6  7  8  9 10]
[2 8 7 6 5 1 3 4 0]
-------------------------------------
[10  9  8  7  6  4  3  2  1]
[0 4 3 1 5 6 7 8 2]


In [63]:
np.sort(x)[::-1]

array([10,  9,  8,  7,  6,  4,  3,  2,  1])

In [64]:
#Sorting along rows or columns
rand = np.random.RandomState(42)
x = rand.randint(0,10,(4,6)) #In range of 0-10 integers it will create a 4X6 array
print(x)
print('-------------sorting by column----------------')
print(np.sort(x, axis = 0)) #sorting of each column
print('-------------sorting by row----------------')
print(np.sort(x,axis=1)) #sorting of each row

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
-------------sorting by column----------------
[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
-------------sorting by row----------------
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


# $31-08-2023$

In [12]:
#Structured array:
import numpy as np
dtype = [('person_name','U9'),
         ('person_age','i8'),
         ('is_programmer', 'bool')]
data = np.array([('Ram',25,True),
                 ('sita',22,False),
                 ('lakshman',20,False),
                 ('arjun',30,True)],dtype = dtype)

print(dtype)
print(data)

[('person_name', 'U9'), ('person_age', 'i8'), ('is_programmer', 'bool')]
[('Ram', 25,  True) ('sita', 22, False) ('lakshman', 20, False)
 ('arjun', 30,  True)]


In [13]:
data['person_name'] # accessing columns or attributes in data base

array(['Ram', 'sita', 'lakshman', 'arjun'], dtype='<U9')

In [5]:
data[0] #accessing the rows or records

('Ram', 25, True)

In [6]:
data[np.where(data['person_name'] == 'lakshman')] #returns only the data according to the person name only if it is lakshman

array([('lakshman', 20, False)],
      dtype=[('person_name', '<U9'), ('person_age', '<i8'), ('is_programmer', '?')])

In [7]:
sorted_data = np.sort(data,order='person_age')[::-1] #sorts the whole dataset in the order of 
print(sorted_data)

[('arjun', 30,  True) ('Ram', 25,  True) ('sita', 22, False)
 ('lakshman', 20, False)]


In [8]:
data[-2:]["person_name"]

array(['lakshman', 'arjun'], dtype='<U9')

In [23]:
# Aggregation:

print("average_age = ",np.mean(data['person_age']))
print("maximum_age = ",np.max(data['person_age']))
print("minimum_age = ",np.min(data['person_age']))
print('standard deviation = ',np.std(data['person_age']))

#Filtering:
a = data[data['person_age']<26]
print('below 26 age = ',a)

#above 25
a = data[data['person_age']>25]
print('above 25 age = ',a)

#know python
a = data[data['is_programmer'] == True]
print('Know python = ',a)

average_age =  24.25
maximum_age =  30
minimum_age =  20
standard deviation =  3.766629793329841
below 26 age =  [('Ram', 25,  True) ('sita', 22, False) ('lakshman', 20, False)]
above 25 age =  [('arjun', 30,  True)]
Know python =  [('Ram', 25,  True) ('arjun', 30,  True)]
